### ISSUE TITLE
Feedback по "bem-tools - Создание блока"

### ISSUE THREAD

**Issue by raining** [bem-site/bem-method#220]
> Создание блока
> 
> bem create block b-my-block
> По умолчанию блок создается с набором файлов для всех технологий (BEMHTML, CSS, JS).

Не создаст, потому что выдается:

`WARNING!`
`Command "bem create block" is deprecated!`
`It will be removed in bem-tools@1.0.0, please use`bem create -b ...`command instead.`

`You should specify techs to create using --force-tech, -T or --add-tech, -t options`

При неправильной попытке создать по подсказкам из терминала команду вываливается стектрейс, например 

`TypeError: Cannot call method 'charAt' of undefined
    at Object.exports.normalize (path.js:336:27)
    at Object.exports.isPath (/usr/local/lib/node_modules/bem/lib/util.js:506:17)`
   ....

При этом `bem create block -T css b-my-block` блок создает, но команда же deprecated?

PS: сайт удобно сделан, технология интересная, спасибо!

**Comment by raining** [comment]
https://ru.bem.info/tools/bem/bem-tools/commands/#Создание-блока-1

**Comment by raining** [comment]
Как я поняла, там еще зависит, откуда вызывать create, написав просто bem create или например ./node_modules/.bin/bem create. Я пробовала делать команды выше без создания готового проекта (просто до этого сделала `bem create level blocks`, просто посмотреть результаты команд). Либо можно как-то уточнить в этом блоке страницы, что команда немного устарела (ибо можно надолго зависнуть на этом абзаце при изучении), либо просто как-то убрать ибо дальше все равно идут корректные команды.

PS: мой монолог по проблеме закончен)

**Comment by zxqfox** [comment]
Feedback — во! :+1:

**Comment by vithar** [comment]
Не актуально.
