### ISSUE TITLE
Feedback for FAQ: Как писать стили для текста из БД

### ISSUE THREAD

**Issue by ihorzenich** [bem-site/bem-method#280]
В FAQ не хватает вопроса «как писать стили для текста из БД?» - ответ: «используя блок .b-text»: http://delka.github.io/talks/webcamp/2015/bem/?full#88

**Comment by gela-d** [comment]
@delka Игорь, спасибо!
/ cc @innabelaya

**Comment by innabelaya** [comment]
@delka @gela-d спасибо, подумаем, как и куда написать. Это больше похоже на how to?, чем на FAQ.

**Comment by vithar** [comment]
Это очень специфично и мы не будет выносить такое в FAQ.
