### ISSUE TITLE
Feedback for "Naming convention"

### ISSUE THREAD

**Issue by Undistraction** [bem-site/bem-method#337]
Hi,

These docs are an improvement, but the areas that need clarity are (I think I know the answers, but they need to be added to the docs):

1. What happens when a component / block contains another component / block. How does the classing interact. Is there overlap? Can the child of one block be the root of another block? `header-button Button`

2. Can a child also have a modifier? In your examples it is always the root element that has a modifier. Is this OK `block-name__elem-name_mod-name`. If this is not allowed, how should it be handled. For example a button with an icon vs a button with a large icon.

3. How do you handle breakpoints? For example if you have a class of `sidebar_position_left` how do you position the element to the right at a breakpoint without leaving a class that is now incorrect on the element? Obviously hardcoding 'left' might be a bad idea, but the same could be true for any style added by a class that is overridden at a breakpoint.

4. If you specialise a block, for example `data_table` vs `data-table_specialised` how do you then style elements. Is `data-table_specialised__element` correct? Or should you nest `data-table__specialized data_table__element`? This is a really important part of naming that I have almost never seen discussed.

With clarity on these kind of issues in the docs, I think peoples use of BEM naming would be much more consistent.

**Comment by tadatuta** [comment]
@Undistraction Thank you!

> 1. What happens when a component / block contains another component / block. How does the classing interact. Is there overlap? Can the child of one block be the root of another block? header-button Button

Does this [part of definitions](https://en.bem.info/method/definitions/#bem-tree) answer the question?

> 2. Can a child also have a modifier?

Is [this chapter](https://en.bem.info/method/naming-convention/#element-modifier) an answer to the question?

> 3. How do you handle breakpoints?

If there's a need to change something in runtime with just CSS (MQ) it should be named with some generic name which suits to any possible value. Or use JS to change a class on DOM node.

> 4

Looks like [this](https://en.bem.info/tools/bem/bem-naming/#common-misconceptions) should be an answer?

// cc @innabelaya let's add the answers to docs?

**Comment by Undistraction** [comment]
Hi,

> 1. Does this part of definitions answer the question?

No. It doesn't show me what to do when a search field block is in another block but needs to be laid out differently for that block. Does it become an element of the block that contains it as well as its own block?
What if it's own elements need to be laid out slightly differently when within different blocks? Should it get multiple specialised classes for different situations (`search-field_layout_minimal`, `search-field_layout_single_line`) or should the block that contains it supply a class that alters its layout: (`header__search-field`, sidebar__search-field`). It also doesn't talk the latter situation, for example:

```
<header class="header">
  <form class="header__search_form form form_search">
    ...
  </form>
</header>
```

In this case, which order is preferred? The containing block's element first ('header__search_form`) or the form's own block classes (`form form_search`). Obviously the declaration order in the `class` attribute will not effect specificity, but a rule would help make things consistent (I prefer the former). In this situation how is specificity handled? It appears that the only thing to govern which of these classes *wins* is source order which is very fragile. I think this is a really important part of BEM naming that needs to be thoroughly discussed - Alongside all the benefits of flattening specificity, how do you deal with the massive disadvantage - the fact that everything now has the same specificity, leading to race-conditions and a dependence on source order.

> 2. Is this chapter an answer to the question?

Yes, but it would make things clearer to say something in the intro to modifiers like:

> Modifiers can be applied to both a block and its elements.

Incidentally, I have seen modifiers used on both block and element in the same class in the wild (`block_modifier__element_modifier`). Explaining whether or not this is a good idea and if not, what the alternative is would also be helpful here. You actually [link](https://en.bem.info/tools/bem/bem-naming/#common-misconceptions) to the answer in your response to my fourth point, but why is this useful information not in the BEM Naming section? There is lots of useful information about naming in other locations such as the FAQ, but I think it needs to be consolidated into the BEM Naming section along with more examples.

> 3. How do you handle breakpoints?

No. I see no mention of BEM naming should work with breakpoints.

> If there's a need to change something in runtime with just CSS (MQ) it should be named with some generic name which suits to any possible value. Or use JS to change a class on DOM node.

Have you looked at Harry Robert's use of Media Queries  [here](http://csswizardry.com/2015/08/bemit-taking-the-bem-naming-convention-a-step-further/) under the heading *Responsive Suffixes*. I suppose this ties into whether or not you want people to adopt BEM naming separately from the rest of the BEM architecture. I think it's a really powerful thing in its own right, and is being used widely on projects with little or no JavaScript.  For these devs, the use of media queries (and the application of state through minimal toggling of classes through JS is a fundamental part of their process, so the idea of directly setting styles with JS is not going to cut it. 

> 4 Looks like this should be an answer?

No. That actually answers a different question (which I talk about above). My fourth point has nothing to with this, but deals with how to handle a specialised block. Hopefully if you reread it you will see.

I suppose a lot of these questions come back to the question - Do you see the naming aspect as a thing in its own right, or just a part of the overall BEM project - Perhaps some of my questions are not so relevant if you intend the naming only to be used with everything else in a JavaScript-centric project, but to someone like me (and many others) who are using or trying to use these naming conventions in projects with little or no JavaScript, these are fundamentally important parts of the naming, and surely the point of a set of rules governing naming is that they cover all these cases. Indeed that is what makes such sets of rules powerful when used on a team (as you of course know). If these naming conventions were more comprehensive and I could point other devs to them it would give us a really powerful shared language. At the moment they get halfway there, then leave lots of grey areas that inhibit standardisation. Apart from anything else I think you would find a greatly increased adoption.

Finally, some kind of guidance on when to use a single modifier value vs a key value pair would be good. For example why isn't `form_search` `form_function_search`. An example of where a key value pair should be used would be helpful.

I'm really happy to continue this dialogue if you would find it helpful. I am also in the process of incorporating BEM naming into a project with a small team, so I am seeing first-hand how people are confused and the places where docs are lacking.

**Comment by innabelaya** [comment]
@Undistraction Thank you very much for your detailed answer! 
Your notes help us to improve our documentation. 
We will add the correct answers to docs.
If you have more questions or you need some clarifications for our documents, create an issue or ask our team on [forum](https://en.bem.info/forum/).
