### ISSUE TITLE
Feedback for "FAQ"

### ISSUE THREAD

**Issue by Eediter** [bem-site/bem-method#377]
По-моему, в параграфе **Почему нельзя делать общий сброс стилей (reset)**, в части про примеры на SASS, подразумевается `@extend`, а не `@include`.

То есть:

```
.menu {
    @extend %reset-list;
}
```

**Comment by tadatuta** [comment]
Почему? Речь ведь идет о миксине: http://sass-lang.com/guide#topic-6

**Comment by Eediter** [comment]
> Если в проекте не используется CSS-оптимизатор, который **объединяет селекторы с одинаковым набором правил**, можно применить CSS-препроцессор.

То есть подразумевается экстенд внутри миксина? Или результат работы препроцессора не про `.menu, .list {}`?

**Comment by innabelaya** [comment]
FAQ was updated. The answer to this question does not contain such example now.
