### ISSUE TITLE
Тег <br> в тексте документации

### ISSUE THREAD

**Issue by shdq** [bem-site/bem-method#393]
На страницах [соглашение по наименованию](https://ru.bem.info/methodology/naming-convention/) и [организация файловой системы](https://ru.bem.info/methodology/filesystem/) в нескольких местах тег `<br>` не интерпретируется.

**Comment by shdq** [comment]
Туда же `<blockquote>` на странице [истории](https://ru.bem.info/methodology/history/).

**Comment by godfreyd** [comment]
Не нашел. Возможно проблема была решена, а задачу не закрыли.
