### ISSUE TITLE
Few mistakes in "История создания"

### ISSUE THREAD

**Issue by DudaGod** [bem-site/bem-method#429]
https://ru.bem.info/methodology/history/#Зарождение-основ-методологии
spelling mistake - Верстка **большоего** проекта

https://ru.bem.info/methodology/history/#Верстка-независимыми-блоками
Tag p should be in tag blockquote

**Comment by godfreyd** [comment]
The first part: "https://ru.bem.info/methodology/history/#Зарождение-основ-методологии
spelling mistake - Верстка большоего проекта"  is fixed https://github.com/bem/bem-method/pull/435/commits/3392eea65ab91c340e8df2f5cad098caf7307d45

**Comment by godfreyd** [comment]
tag blockquote is correct
