### ISSUE TITLE
Неструктурированный раздел

### ISSUE THREAD

**Issue by myshov** [bem-site/bem-method#483]
В разделе https://ru.bem.info/methodology/js/#Работа-с-модификаторами есть абзацы:

> Модификаторы могут задавать блокам определенные состояния. Логика работы блока реализуется в JavaScript и описывается с помощью состояний. Перевод блока в другое состояние может производиться при помощи установки/снятия модификатора. Изменение модификатора создает событие, которое можно использовать для работы с блоком.
> 
> Например, чтобы отметить чекбокс, блоку checkbox нужно установить модификатор checked в значение true.

При этом первый абзац это перечисление каких-то особенностей присущих работе с модификаторами, поэтому логичнее было бы сделать его в виде списка, с соответствующим объяснением, что пытаются раскрыть эти аргументы. Второй абзац пытается привести пример работы с модификатором, но какую особенность из предыдущего абазца он покрывает абсолютно неочевидно.

**Comment by godfreyd** [comment]
> При этом первый абзац это перечисление каких-то особенностей присущих работе с модификаторами

Это не перечисление особенностей, а последовательно связанные предложения. Второй абзац свяжем с последним предложением из первого.

**Comment by myshov** [comment]
> Это не перечисление особенностей, а последовательно связанные предложения. 

Ну ок, может действительно это касается особенностей моего восприятия русского текста :)

Но по крайней мере надо добавить какую-то вводную часть, чтобы подготовить читателя к тому. Кажется, что так будет проще:

> Работа с модификаторами инициирует следующий цикл:
1. Установка /снятие модификаторов могут задавать блокам определенные состояния, при этом логика работы блока реализуется в JavaScript и описывается с помощью состояний.
2. Изменение модификатора создает событие, которое можно использовать для работы с блоком.

При этом из такого изложения сразу понятно, что происходит и что из чего вытекает.

**Comment by innabelaya** [comment]
Документ обновлен и переработан https://github.com/bem-site/bem-method/pull/587
