### ISSUE TITLE
Вводящее в заблуждение утверждение

### ISSUE THREAD

**Issue by myshov** [bem-site/bem-method#484]
В примере к разделу "Реакция на изменение модификаторов"  https://ru.bem.info/methodology/js/#Реакция-на-изменение-модификаторов есть фраза:

> Такой подход дает возможность:
> 
> Реагировать на модификатор независимо от способа его установки/снятия (через JavaScript API: block('button').setMod('focused') или пользователь установил/снял фокус курсором).

Установка модификатора при установке фокуса пользователем на dom-элемент не может происходить сама по себе, это делает какой-то js-код. Поэтому часть фразы "или пользователь установил/снял фокус курсором" лишняя.

Или здесь имелось в виду что-то другое?

**Comment by godfreyd** [comment]
Здравствуйте!
Фраза "или пользователь установил/снял фокус курсором" определенно не лишняя.  В скобках указано противопоставление, т.е. мы проверяем каким образом был выставлен фокус:
- за счет курсора мыши;
- за счет какого-то другого JavaScript вызова.

Понятно, что в обоих случаях модификатор меняется при помощи Java Script, но именно источник требования "изменить модификатор" может быть разный.

**Comment by myshov** [comment]
> Такое разделение сделано по простой причине. Если пользователь сам кликнул по какому-то блоку, он знает куда кликнул и этот блок не нужно дополнительно выделять, например, оранжевой рамкой. Второй вариант, когда пользователь нажал что-то на клавиатуре и блок из-за этого встал в фокус. В этом случае нужна оранжевая рамка, чтобы понять, куда перешел фокус.

В этом объяснении я вижу противоречие тому, что написано в документации:

> Реагировать на модификатор независимо от способа его установки/снятия (через JavaScript API: block('button').setMod('focused') или пользователь установил/снял фокус курсором).

То есть модификатор ставится в обоих случаях (в вашем примере оранжевая рамка появится всегда) и если пользователь щелкнул по полю ввода и если установка модификатора была инициирована программно.

Как человеку, который впервые читает документацию по БЭМу, причина, зачем говорить об источнике инициации изменений в разделе о преимуществах, остается непонятной. Логичнее вынести информацию об этом (если она действительно так необходимо) в независимый абзац.

**Comment by godfreyd** [comment]
> в вашем примере оранжевая рамка появится всегда
 Модификаторы разные

**Comment by godfreyd** [comment]
> В этом объяснении я вижу противоречие тому

Мое объяснение касалось источников инициализации, чтобы вы понимали, что  фраза "или пользователь установил/снял фокус курсором" не является лишней. Источников инициализации очень много и их отдельное описание выходит за рамки методологии БЭМ.

**Comment by myshov** [comment]
Ну вот я о том же. И все-таки зачем упоминать это в пункте, который посвящен преимуществам? Кажется, что это предложение:

> Реагировать на модификатор независимо от способа его установки/снятия (через JavaScript API: block('button').setMod('focused') или пользователь установил/снял фокус курсором).

старается донести несколько идей сразу и это не приносит понятности в документацию.

**Comment by innabelaya** [comment]
Документ обновлен https://github.com/bem-site/bem-method/pull/587
