### ISSUE TITLE
Отсутствие связи между предложениями

### ISSUE THREAD

**Issue by myshov** [bem-site/bem-method#488]
В главе https://ru.bem.info/methodology/js/#Как-перейти-на-javascript-по-БЭМ написано:

> Чтобы реализовать сразу все идеи БЭМ в вашем проекте, необходимо использовать фреймворк i-bem.js:
> - работать в единых терминах блоков, элементов и модификаторов во всех технологиях;
> - создавать независимые компоненты — блоки — на уровне JavaScript;

Должно быть так?

> Чтобы реализовать сразу все идеи БЭМ в вашем проекте, необходимо использовать фреймворк i-bem.js, его использование позволит:
> - работать в единых терминах блоков, элементов и модификаторов во всех технологиях;
> - создавать независимые компоненты — блоки — на уровне JavaScript;

**Comment by godfreyd** [comment]
Здравствуйте. Поправим.
