### ISSUE TITLE
Двусмысленный заголовок раздела

### ISSUE THREAD

**Issue by myshov** [bem-site/bem-method#490]
В разделе с заголовком "Взаимодействие блока с его элементами" https://ru.bem.info/methodology/js-principles/#Взаимодействие-блока-с-его-элементами говорится, по сути, о том как правильно взаимодействовать с элементами блока, из внешнего мира - других блоков. Информация о том как блок взаимодействует со своими собственными элементами нет (как я понял это особенности реализации, поэтому об этом информации нет).

В общем, предлагаю переименовать раздел в "Взаимодействие с элементами других блоков".

**Comment by vithar** [comment]
Про взаимодействие со своими элементами тоже нужно написать.

**Comment by innabelaya** [comment]
@myshov Спасибо. Раздел переименован в «Взаимодействие блока с элементами», так как про взаимодействие блока со своими элементами там все-таки тоже говорится. 
https://github.com/bem-site/bem-method/commit/dc71314afd1af9a275fb6db2bb451abfa3a28ba6
