### ISSUE TITLE
Неясный пример в истории структуры репозитория

### ISSUE THREAD

**Issue by myshov** [bem-site/bem-method#495]
В разделе https://ru.bem.info/methodology/history/#Структура-репозитория-1 есть пример того, как был структурирован CSS:

> ```
> common/
>   css/
>     b-dropdown/
>       arr/
>         b-dropdown.arr.css
>         b-dropdown.arr.ie.css
>         b-dropdown.css
>         b-dropdown.ie.css
> ```
> 
> Всё, что находилось в опциональном CSS (файлах b-dropdown_arr.css), вынесено в директории (arr/b-dropdown.arr.css). В основном файле блока стало меньше кода.

При этом, что такое опциональный CSS не совсем понятно. Из предыдущего изложения я бы мог предположить что это ie-специфичный код. Но здесь говорится о файле `b-dropdown_arr.css` (наверно имеется в виду `b-dropdown.arr.css`). Почему именно он, а не (`b-dropdown.arr.ie.css` и `b-dropdown.ie.css` из текста неясно.

**Comment by innabelaya** [comment]
@myshov  Thank you! Fixed.
https://github.com/bem-site/bem-method/commit/f99ae20a72629484819bc9bc2e0423458065562c
