### ISSUE TITLE
nowrap элементы списка на сайте не влязят на экран при чтении с мобильного

### ISSUE THREAD

**Issue by vityas-off** [bem-site/bem-method#502]
При этом нет возможности проскроллить и прочитать названия до конца.
![screenshot_20160911-231401](https://cloud.githubusercontent.com/assets/15840124/18420217/1f53ed82-7876-11e6-9e7a-d1c038178d0a.png)

**Comment by vithar** [comment]
Можно попробовать уменьшить размер шрифта на страницах, давай посмотрим вместе, что можно сделать.

**Comment by vithar** [comment]
Или можно для article добавить `word-wrap: break-word`

**Comment by innabelaya** [comment]
@vithar Завела issue в bem-site/bem.info, потому что задача про разработку: bem-site/bem.info#233.
Здесь закрываю.
