### ISSUE TITLE
Свитчер языка в шапке

### ISSUE THREAD

**Issue by chat-du-cheshire** [bem-site/bem-method#517]
В свитчере UK ассоциируется с United Kingdom, для украинского правильнее было  бы UA.

**Comment by godfreyd** [comment]
Привет! Код языка выбран в соответствии с принятыми международными стандартами:
[Коды языков](https://ru.wikipedia.org/wiki/Коды_языков ).
[ISO_639](https://ru.wikipedia.org/wiki/ISO_639).
