### ISSUE TITLE
Добавить в документацию график веса селекторов

### ISSUE THREAD

**Issue by belozer** [bem-site/bem-method#529]
Вложенные селекторы. Визуально видна тяжесть селекторов.
![image](https://cloud.githubusercontent.com/assets/1655916/20685283/da10af80-b5c4-11e6-8b40-0f950cef330c.png)

А такой график, если использовать БЭМ
![image](https://cloud.githubusercontent.com/assets/1655916/20685339/0920d340-b5c5-11e6-9ede-5b403b45de05.png)

(пики на БЭМ графике - это косяк парсинга моего CSS)

Можно оставить ссылку на онлайн парсер. [Взвесь свой CSS](https://jonassebastianohlsson.com/specificity-graph/)

**Comment by tadatuta** [comment]
Как по мне, график без пояснений выглядит примерно как график сферического коня в ваууме :)

Взяли **какой-то** код и **какой-то другой** код, а потом сравнили. Получили **какой-то график**. Осталось сделать на его основе какой-то вывод ;)
