### ISSUE TITLE
broken link on https://en.bem.info/methodology/quick-start/

### ISSUE THREAD

**Issue by Frazer** [bem-site/bem-method#534]
Hi, on https://en.bem.info/methodology/quick-start/

you have this link:
Why write the block name in the names of modifiers and elements?  that goes to:
https://en.bem.info/methodology/faq/#why-include-the-block-name-in-names-of-modifier-and-element

it should go to :
https://en.bem.info/methodology/faq/#why-include-the-block-name-in-modifier-and-element-names

**Comment by tadatuta** [comment]
@Frazer Thank you! Fixed in https://github.com/bem-site/bem-method/pull/535
