### ISSUE TITLE
Написать, что на узле может быть только один модификатор с данным именем

### ISSUE THREAD

**Issue by myshov** [bem-site/bem-method#537]
Из БЭМ-чата:

**Alexander Myshov, [22 дек. 2016 г., 22:09]:** 
Привет!
Возможно ли в i-bem удалить модификатор с заданным значением?

**Alexander Myshov, [22 дек. 2016 г., 22:10 (22.12.16, 22:11)]:** 
Например, есть блок, которому соответствует такие модификаторы class="block_type_1 block_type_2" необходимо удалить модификатор block_type_2

**Nikolay Chursin, [22 дек. 2016 г., 22:11]:** 
Значения модификатора же взаимоисключающие, не?

**Sergey Belozyorcev, [22 дек. 2016 г., 22:12]:** 
В единицу времени может быть только одно значение из группы (в данном случае только один type может существовать)

**Alexander Myshov, [22 дек. 2016 г., 22:15]:** 
методология это не запрещает
по крайней мере в доках ничего про такие ограничения не встречал

**Sergey Belozyorcev, [22 дек. 2016 г., 22:18]:** 
у тебя 2 модификатора в html. «block_size_l block_size_m» Как браузер определит какой размер должен быть?

**Alexander Myshov, [22 дек. 2016 г., 22:18]:** 
это частный случай

**Sergey Belozyorcev, [22 дек. 2016 г., 22:18]:** 
Это не частный случай
Опиши конкретно задачу и тогда ответ будет более правильным

**Alexander Myshov, [22 дек. 2016 г., 22:20]:** 
контрпример, карточка заказа может иметь разные статусы: card_status_correct и card_status_in-process
я понимаю, что это можно разрулить непересекающимся набором модификаторов
но не встречал такое требование в доке

**Nikolay Chursin, [22 дек. 2016 г., 22:21]:** 
Модификатор "ключ-значение" уже своим названием, имхо, предполагает, что у одного ключа может быть одно и только одно значение в один момент времени.

**Vitaly Harisov, [22 дек. 2016 г., 22:21]:** 
Модификатор как атрибут в html

**Alexander Myshov, [22 дек. 2016 г., 22:22]:** 
ну да если с этой стороны смотреть то да

**Vitaly Harisov, [22 дек. 2016 г., 22:22]:** 
Не может быть два одинаковых атрибута у одного узла с разными значениями
С другой стороны смотреть и не надо

**Yaroslav Usenko, [22 дек. 2016 г., 22:22]:** 
Блин а в доке реально этого нет

**Alexander Myshov, [22 дек. 2016 г., 22:23]:** 
Есть такое утверждение:
"Модификатор представляет собой пару: имя и значение."
Но имхо этого недостаточно

**Vitaly Harisov, [22 дек. 2016 г., 22:23]:** 
Поставьте задачу на доработку доки

**Alexander Myshov, [22 дек. 2016 г., 22:24]:** 
ок

**Comment by vithar** [comment]
Нужно явно написать про это в https://ru.bem.info/methodology/key-concepts/#Модификатор
