### ISSUE TITLE
Пустая стр. в документации

### ISSUE THREAD

**Issue by nicothin** [bem-site/bem-method#539]
https://ru.bem.info/methodology/naming-convention/ — внизу есть ссылки на bem-naming
http://take.ms/3LcSc — при переходе на https://ru.bem.info/toolbox/sdk/bem-naming/ — пустота

**Comment by innabelaya** [comment]
@nicothin Спасибо, что написали нам. Документация по bem-naming доступна только на английском языке. Сейчас при переходе на https://ru.bem.info/toolbox/sdk/bem-naming/ появляется английская версия документа. 
Если есть возможность и желание, вы можете помочь нам с переводом — https://github.com/bem-site/translation
