### ISSUE TITLE
Feedback for "БЭМ: проекты и обратная связь"

### ISSUE THREAD

**Issue by Grimfri** [bem-site/bem-method#544]
Внизу [анкеты](https://ru.bem.info/feedback/) два почти одинаковых чекбокса (Я даю согласие...). И еще при нажатии в боковом меню на пункт "Благодарности" перекидывает на главную страницу.

**Comment by tadatuta** [comment]
Чекбоксы — это требование юристов, основанное на требованиях российского законодательства, тут мы, к сожалению, упростить не можем :(

А пункт меню «Благодарности» исчезнет с остатками старого дизайна — содержимое этой страницы действительно перекочевало в подвал на главную в виде «Ядвига и Яцек Даниц — спасибо за домен!»
