### ISSUE TITLE
Стили сайта: двигать li, а не a

### ISSUE THREAD

**Issue by nicothin** [bem-site/bem-method#545]
Большие области, лежащие поверх текстового контента, порой, не позволяют комфортно работать с выделением текста.
http://take.ms/3SqH1
Хорошо бы сдвигать не ссылки внутри пунктов списка, а сами пункты, дабы не загораживать ими текст страницы.

**Comment by vithar** [comment]
Fixed in https://github.com/bem-site/bem.info/pull/184
