### ISSUE TITLE
Не работает в хроме на виндоус  7 32

### ISSUE THREAD

**Issue by mirspasaka** [bem-site/bem-method#549]
Здравствуйте, решил вот узнать что такое этот БЭМ  зашел на сраничку, нажал быстрый старт и облом: форма с именем пользователя и нажать кнопка не работают. Просто ничего не происходит.

**Comment by innabelaya** [comment]
@mirspasaka Добрый день! Можете описать проблему немного подробнее, например, какие шаги из инструкции вам удалось выполнить, какие нет?

**Comment by mirspasaka** [comment]
https://ru.bem.info/platform/tutorials/quick-start-static/   здесь туториал и написано: 
"Что должно получиться
Страница приветствия пользователя, содержащая поле ввода, кнопку и текст. При нажатии на кнопку страница обновляется и текст дополняется значением, введенным в поле." 
И прикреплена  картинка? Я подумал, что пример, который получится - это рабочий пример: то есть надо ввести имя пользователя и оно появится:)  Несовпадение в голове от того, что выходит в примере мы учимся прикреплять картинку, а не делать формочку с кнопкой.

**Comment by innabelaya** [comment]
@mirspasaka Спасибо за ваш фидбек. Попробуем более явно указать в документации, что это картинка-пример того, как должна выглядеть собранная страница. И обсудим возможность появления в подобных документах встроенных примеров.
