### ISSUE TITLE
padding or margin?

### ISSUE THREAD

**Issue by alberto-marin** [bem-site/bem-method#564]
At [External geometry and positioning](https://en.bem.info/methodology/css/#external-geometry-and-positioning) where it says:

> The button block includes a **padding** of 30px, which may prevent its reuse.
...
> Now the button block is independent and universal, because it doesn't specify any **padding**.

and following the code from de example, shouldn't be **margin** instead of padding?

<img width="762" alt="screen shot 2017-04-01 at 17 51 54" src="https://cloud.githubusercontent.com/assets/10046225/24580701/6d0743f8-1704-11e7-960e-a3fe5e9c27e5.png">

**Comment by tadatuta** [comment]
@alberto-marin thank you!
fixed in https://github.com/bem-site/bem-method/pull/565
