### ISSUE TITLE
Bad redirect link

### ISSUE THREAD

**Issue by Tecayehuatl** [bem-site/bem-method#571]
In this [page](https://en.bem.info/methodology/key-concepts/) the achor that wrap the "A block or an element: when should I use which?" text should be redirected to this [page section](https://en.bem.info/methodology/faq/#a-block-or-an-element-when-should-i-use-which) instead of this [page section](https://en.bem.info/methodology/faq/#a-block-or-an-element-when-should-i-use-which)

**Comment by innabelaya** [comment]
@Tecayehuatl thank you! Fixed in https://github.com/bem-site/bem-method/commit/a3eef462509b5c95dcde951f6e423a59edaf339a
