### ISSUE TITLE
The modifiers are not BEM

### ISSUE THREAD

**Issue by engelfrost** [bem-site/bem-method#575]
Original title: The modifiers are not BEM!

This is not the BEM way of writing modifiers. The whole point of BEM is to write it as one class name: block__element--**modifier**! https://en.bem.info/methodology/css/#modifiers

**Comment by tadatuta** [comment]
@engelfrost, why do you think it's not the BEM way?

Kinda funny to hear that info about modifiers on official BEM site maintained by the authors of BEM methodology is wrong ;)

**Comment by engelfrost** [comment]
Sorry to make such bold claims, it was a little drastic of me. Thanks for replying in good spirit. If this is the original BEM project I assume I've learned another BEM dialect. 

My understanding was that modifiers were added with the `--modifier` suffix. Without that difference in syntax I do not see a clear distinction between modifiers and mixes as it is written in your documentation.
