### ISSUE TITLE
Ошибка в адресе ссылки на странице "Быстрый старт".

### ISSUE THREAD

**Issue by DaggLo** [bem-site/bem-method#596]
В разделе Модификатор / Принципы работы с модификаторами, ссылка с адресом
```/methodology/faq/#Зачем-писать-имя-блока-в-именах-модификаторов-и-элементов```

должна иметь адрес
```/methodology/faq/#Зачем-указывать-имя-блока-в-именах-модификаторов-и-элементов```

**Comment by innabelaya** [comment]
@DaggLo Спасибо! исправлено https://github.com/bem-site/bem-method/commit/ae547898b492d1235146607e755f7742d5d743ff. Обновили на сайте.
