### ISSUE TITLE
.article-rewind_type_floating .article-rewind__next при (max-device-width: 568px) показывается и плавает по середине экрана

### ISSUE THREAD

**Issue by MariaEvstropova** [bem-site/bem-method#599]
.article-rewind_type_floating .article-rewind__next при (max-device-width: 568px) показывается и плавает по середине экрана. Это затрудняет чтение на мобильных устройствах.

**Comment by tadatuta** [comment]
@MariaEvstropova спасибо, починим

**Comment by vithar** [comment]
Fixed.
