### ISSUE TITLE
Не рабочая ссылка по адресу: "https://ru.bem.info/methodology/js/"

### ISSUE THREAD

**Issue by Alexey808** [bem-site/bem-method#603]
Адрес:	"https://ru.bem.info/methodology/js/"
Раздел:    "Работа с уровнями переопределения"
Строка:    "Подробнее о подключении библиотеки в проект."
Время:     21:04 19.07.2017
Где "Подробнее" является ссылкой на дополнительный ресурс.

**Comment by tadatuta** [comment]
@Alexey808 спасибо, исправлено в https://github.com/bem-site/bem-method/commit/09f2118588b12973a847c6ffbd7b989841c02efc
