### ISSUE TITLE
Длинный <code> вылазит на маленьких экранах

### ISSUE THREAD

**Issue by MikeDevice** [bem-site/bem-method#606]
Заметил на [этой странице](https://ru.bem.info/methodology/quick-start/), что `имя-блока_имя-модификатора` и `имя-блока__имя-элемента_имя-модификатора` на маленьких экранах не помещаются и их попросту не видно.

![image](https://user-images.githubusercontent.com/7154108/28568144-6cd96878-713d-11e7-8bac-5911a4e2543d.png)

**Comment by vithar** [comment]
Дубль к https://github.com/bem-site/bem-method/issues/502
