### ISSUE TITLE
Naming convention: camelCase и PascalCase

### ISSUE THREAD

**Issue by uoziod** [bem-site/bem-method#609]
В [документации](https://en.bem.info/methodology/naming-convention/) вы ссылаетесь на PascalCase именуя его camelCase'ом. Понимаю, что вопрос легко претендует на спорный, тем не менее большинство источников мною сейчас найденных на данный момент склоняются в пользу camelCase и PascalCase.

**Comment by tadatuta** [comment]
@uoziod Спасибо, исправим!

// cc @innabelaya

**Comment by innabelaya** [comment]
@uoziod @tadatuta Спасибо! Исправлено в новой версии документа: https://github.com/bem-site/bem-method/pull/610
