### ISSUE TITLE
Ошибка в html при переходе внутри страницы JavaScript по БЭМ

### ISSUE THREAD

**Issue by Dejier** [bem-site/bem-method#619]
Страница: JavaScript по БЭМ - https://ru.bem.info/methodology/js/
Описание ошибки: нельзя выполнить переход по быстрой ссылке внутри страницы "Как перейти на JavaScript по БЭМ"

Суть ошибки:
Внутри: 
a href="#Как-перейти-на-JavaScript-по-БЭМ">Как перейти на JavaScript по БЭМ</a

Ожидаем переход к элементу c таким же id, но не находим. Разное написание слова "javascript" - регистр имеет значение.

h2 class="article__heading article__heading_2" id="Как-перейти-на-javascript-по-БЭМ"><a href="#Как-перейти-на-javascript-по-БЭМ" class="article__heading-anchor"></a>Как перейти на JavaScript по БЭМ</h2

**Comment by innabelaya** [comment]
@Dejier Спасибо! Исправили https://github.com/bem-site/bem-method/commit/2a0196b41f3203eea8cefc42d43114d86857c4b9
