### ISSUE TITLE
typo on https://en.bem.info/methodology/css/#combined-selectors

### ISSUE THREAD

**Issue by supimon** [bem-site/bem-method#622]
the change is:
under "Combined Selectors", underneath the example code, the sentence depicting the class name is erroneous. 
It currently reads:
".... defined in the button.button_theme_islands selector. ."

whereas it should be

".... defined in the .button.button_theme_islands selector. ."
with a period before the first class name.

**Comment by vithar** [comment]
Thank you, this is already fixed.
