### ISSUE TITLE
Не работающие якори

### ISSUE THREAD

**Issue by vladsad** [bem-site/bem-method#630]
Почему в русскоязычной и украинской документациях не работают #якори,по крайней мере на первых её страницах Быстрый старт и тд, у закладки пустой  id="-" ?

![selection_095](https://user-images.githubusercontent.com/5551873/31488322-f779fe0c-af45-11e7-9dc7-c70a80d94974.png)

![selection_096](https://user-images.githubusercontent.com/5551873/31488320-f75c0924-af45-11e7-835d-b362309775f4.png)

**Comment by innabelaya** [comment]
@vladsad 
Знаем, чиним. В ближайшее время исправим.

**Comment by godfreyd** [comment]
Исправили.
