### ISSUE TITLE
Послетали якоря ⚓ + несоответствие разделов

### ISSUE THREAD

**Issue by lllilllkin** [bem-site/bem-method#631]
Послетали якоря ⚓ в [русскоязычной версии](https://ru.bem.info/methodology/quick-start/) документации

Некоторое несоответствие разделов:
В английском "How do I make an HTML wrapper?" => /methodology/css/
В русском "Использование HTML-оберток" => /methodology/html/

**Comment by innabelaya** [comment]
@lllilllkin Якоря чиним, спасибо!
Разделы в русской и английской версии документов не соответствуют, потому что русская версия документов обновилась, а переводы обновленных документов мы выкладываем по мере готовности. В английской версии тоже есть раздел https://en.bem.info/methodology/html/#using-html-wrappers. А вот перевод документа про CSS еще не обновлен.
