### ISSUE TITLE
Опечатка на странице Соглашение по именованию

### ISSUE THREAD

**Issue by vill** [bem-site/bem-method#636]
Всем привет. На странице https://ru.bem.info/methodology/naming-convention/#Стиль-two-dashes опечатка в слове `имениЯ`:

> Булевые модификаторы отделяются от имения блока или элемента двумя дефисами (--).

**Comment by godfreyd** [comment]
Привет. Спасибо, поправили https://github.com/bem-site/bem-method/pull/637
