### ISSUE TITLE
Не понятно как определять внешнюю геометрию и позиционирование

### ISSUE THREAD

**Issue by OlegGorohov** [bem-site/bem-method#649]
Добрый день.
Из инструкции не совсем ясно как определять внешнюю геометрию и позиционирование: с помощью родительского блока или с помощью элемента. В примере показаны преимущества использования элемента, но в описании сказано про родительский блок.
https://ru.bem.info/methodology/css/#Внешняя-геометрия-и-позиционирование
![image](https://user-images.githubusercontent.com/29440740/33118075-1dabbc92-cf84-11e7-8e1b-ccd65a935eb8.png)

**Comment by godfreyd** [comment]
Привет, элемент `header__button` — это элемент родительского блока `header`. Внешняя геометрия задается через родительский блок, т. е. именно в родительском блоке создаете элемент, пишите стили и затем миксуете к нужному дочернему блоку.

**Comment by OlegGorohov** [comment]
Хм, ясно. Теперь понятно как использовать миксы) Спасибо!
