### ISSUE TITLE
Блоки страницы наползают друг на друга.

### ISSUE THREAD

**Issue by AlexGred** [bem-site/bem-method#652]
Google chrome 62.
[Страница с проблемой](https://ru.bem.info/methodology/html/).
Добавление блоку `.article` `overflow: hidden;` решает проблему.

![1](https://user-images.githubusercontent.com/9657910/33244882-3bc28578-d310-11e7-9de4-c6c9075d3577.png)

**Comment by innabelaya** [comment]
@AlexGred спасибо, про это есть задача https://github.com/bem-site/bem.info/issues/222. Следить и помогать можно в ней.
