### ISSUE TITLE
Проблема с версткой

### ISSUE THREAD

**Issue by neretin-trike** [bem-site/bem-method#661]
В разделах [HTML](https://ru.bem.info/methodology/html/) и [Файловая структура](https://ru.bem.info/methodology/filestructure/) конце статьи, часть примера накладывается на блок article-amendments из-за обтекания по левому краю у элемента code.

![image](https://user-images.githubusercontent.com/26903236/33696819-936466b0-db36-11e7-9669-86509dcba0f2.png)

**Comment by godfreyd** [comment]
@neretin-trike, спасибо, про это есть задача https://github.com/bem-site/bem.info/issues/222 Можно следить в ней.
