### ISSUE TITLE
Орфографическая ошибка в тексте 

### ISSUE THREAD

**Issue by roma-dev** [bem-site/bem-method#665]
в тексте
..logo, search и user, необходимо определ**е**ить отступы..

на стр. https://ru.bem.info/methodology/block-modification/#%D0%98%D0%B7%D0%BC%D0%B5%D0%BD%D0%B5%D0%BD%D0%B8%D0%B5-%D0%B1%D0%BB%D0%BE%D0%BA%D0%B0-%D0%BA%D0%BE%D0%BD%D1%82%D0%B5%D0%BA%D1%81%D1%82%D0%BE%D0%BC

**Comment by ghost** [comment]
Исправлено в #663.
