### ISSUE TITLE
Неправильно работает перенаправление страниц

### ISSUE THREAD

**Issue by vill** [bem-site/bem-method#669]
Всем привет. Если в адресе не указывать завершающий слеш, то перенапрвление происходит на несуществующую страницу, например:

Страница открывается корректно https://en.bem.info/methodology/ убираем последний слеш https://en.bem.info/methodology происходит перенаправление на страницу https://en.bem.info/en/methodology/ со статусом 404, хотя перенаправление должно было происходить на https://en.bem.info/methodology/ или без перенаправления но с отображением того же контента что и для страницы с адресом https://en.bem.info/methodology/.

**Comment by innabelaya** [comment]
@vill Спасибо за фидбек.
сс @vithar @a-lexxx

**Comment by a-lexxx** [comment]
Should be fixed for now.
@vill thanks for your message
