### ISSUE TITLE
Сломаны картинки в меню и методологии

### ISSUE THREAD

**Issue by ghost** [bem-site/bem-method#671]
![2018-01-03 17_56_59-](https://user-images.githubusercontent.com/22275982/34523116-26cbd2a0-f0a7-11e7-8dfe-78ce85ca43c4.png)
![2018-01-03 17_51_45- _](https://user-images.githubusercontent.com/22275982/34523117-26f2a29a-f0a7-11e7-9b40-ff155ceaa605.png)

**Comment by godfreyd** [comment]
Привет. Какой браузер, система. У меня не воспроизводится. Задача не в том репозитории, закрываю, отпиши здесь https://github.com/bem-site/bem.info/issues/248
