### ISSUE TITLE
Неверный пример

### ISSUE THREAD

**Issue by UglyBastard** [bem-site/bem-method#672]
В разделе "Альтернативные схемы именования", "Стиль CamelCase" в примере, имя блока отделено от имени элемента дефисом, в то время как в описании, написано, что разделители имен блоков, элементов и модификаторов совпадают с классической схемой. А классическая схема подразумевает разделение имени блока и имени элемента двумя нижними подчёркиваниями.
![error](https://user-images.githubusercontent.com/34768765/34526087-81e4b5c0-f0cb-11e7-9c3e-aff46d04a200.png)

**Comment by godfreyd** [comment]
Спасибо. @innabelaya, посмотри, пожалуйста. Давай удалим про разделители имен блоков. У блоков их нет.

**Comment by innabelaya** [comment]
@UglyBastard спасибо. Поправили.
