### ISSUE TITLE
Ошибки на страницах сайта

### ISSUE THREAD

**Issue by el-mariachi** [bem-site/bem-method#683]
Привет!
У вас там на некоторых страницах вылезла разметка. Видимо, лишний раз заэкранировалась.

https://ru.bem.info/platform/
https://ru.bem.info/platform/tutorials/quick-start-static/

Например: git <span class="hljs-built_in">clone</span> https://github.com/bem/project-stub.git --depth 1 start-project
Или: компонентов.&lt;br&gt;Позволяет

**Comment by innabelaya** [comment]
@el-mariachi Добрый день! Спасибо! Задачу уже завели здесь: https://github.com/bem-site/bem.info/issues/253
