### ISSUE TITLE
Перепутаны ссылки на prose.io и github.com

### ISSUE THREAD

**Issue by Telichkin** [bem-site/bem-method#687]
В правой колонке на страницах с методологией, например https://ru.bem.info/methodology/quick-start/, ссылка на "Гитхаб" ведет на prose.io, а ссылка на "prose.io" ведет на github.com

![image](https://user-images.githubusercontent.com/12344951/36257579-88814420-1268-11e8-9354-2f91c1ef153e.png)

**Comment by ghost** [comment]
Проблема была в репозитории [bem-site/bem.info](https://github.com/bem-site/bem.info). Она появилась с коммитом [6048061](https://github.com/bem-site/bem.info/commit/60480619694c02e3ea8f170c15588f6802fa980a#diff-bb76c71ac3e4dd6bad735b66691f5b56) 4-го февраля, а с коммитом [4c0a563](https://github.com/bem-site/bem.info/commit/4c0a56365798719b3a257bf7ba654b81083b96e9#diff-bb76c71ac3e4dd6bad735b66691f5b56) 12-го февраля уже была исправлена.
Судя по всему, 15-го февраля версия с этими изменениями ещё не была развёрнута, но сегодня это больше не актуально: ссылки не перепутаны.
