### ISSUE TITLE
Link to 404 page

### ISSUE THREAD

**Issue by kostalakosta** [bem-site/bem-method#690]
![image](https://user-images.githubusercontent.com/19335763/36921586-ec68d57a-1e75-11e8-9b56-ad1bd60f7a0f.png)

**Comment by release-please** [comment]
Страница: [https://ru.bem.info/methodology/naming-convention](https://ru.bem.info/methodology/naming-convention/#%D0%90%D0%BB%D1%8C%D1%82%D0%B5%D1%80%D0%BD%D0%B0%D1%82%D0%B8%D0%B2%D0%BD%D1%8B%D0%B5-%D1%81%D1%85%D0%B5%D0%BC%D1%8B-%D0%B8%D0%BC%D0%B5%D0%BD%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F)

**Comment by godfreyd** [comment]
Thanks guys! Fix https://github.com/bem-site/bem-method/pull/692
