### ISSUE TITLE
Как хранить миксы по БЭМу в стиле nested?

### ISSUE THREAD

**Issue by kulaginds** [bem-site/bem-method#706]
На странице о файловой структуре (https://ru.bem.info/methodology/filestructure/) описывается расположение блоков, элементов, модификаторов, но не миксов.
Перерыл весь сайт, искал во всех issues, не нашел ответа на свой вопрос.

Пользуюсь [bem/project-stub](https://github.com/bem/project-stub) и собираю с помощью gulp.
Попробовал разместить микс как в примере ниже, но в бандл код микса не попал.
<pre>
desktop.blocks/
    body/
        __container/
            body__container.css
    container/
        container.css
</pre>

Благодарю за ответ.

**Comment by tadatuta** [comment]
С точки зрения файловой структуры БЭМ-сущности, размещаемые на DOM-узле через миксы, никак не отличаются от «обычных» БЭМ-сущностей. Т.е. если к узлу миксуется блок, он будет самым обычным блоков на ФС, если миксуется элемент — обычным элементом.

Пример выглядит совершенно правильно. Подозреваю, что проблема кроется в синтаксисе добавления микса в BEMJSON. Либо, если микс добавляется в BEMHTML-шаблоне, то необходимо добавить его в зависимости родительского блока с помощью технологии deps.js (см. https://ru.bem.info/platform/deps/)

**Comment by kulaginds** [comment]
Забыл указать, что для сборки бандла я использую готовый файл декларации, в котором перечисляю используемые блоки.

Не подскажете, как указать в deps-файле зависимость блока body от микса body__container?

Прописал зависимость в файле body.deps.js в папке блока body, но стили микса body__container в бандл так и не подтянулись...
<pre>
({
    block: 'body',
    shouldDeps: [
        { block: 'body__container' }
    ]
})
</pre>

**Comment by tadatuta** [comment]
`body__container` — это не блок, а элемент:

```js
({
    block: 'body',
    shouldDeps: [
        { block: 'body', elem: 'container' }
    ]
})
```

Но меня не покидает подозрение, что что-то не так семантически. Как в итоге BEMJSON целиком выглядит и что в шаблонах написано?

**Comment by kulaginds** [comment]
Вылил реп на гитхаб: https://github.com/kulaginds/bem_example
Я не использовал шаблоны.

**Comment by kulaginds** [comment]
Внимательнее глянул бандл CSS: gulp добавил код из микса в бандл.
