### ISSUE TITLE
https://ru.bem.info/methodology/html/

### ISSUE THREAD

**Issue by slogoz** [bem-site/bem-method#712]
Расположение блока относительно других блоков
Чтобы позиционировать один блок относительно другого блока, используется микс.

В примере блоки header и footer позиционируются на странице с помощью микса с элементами блока page, которым заданы нужные стили. Элементы page__header и page__footer опциональные и применяются к блоку page, если необходимо разместить шапку (page) или подвал (footer) на странице. Блоки page, header и footer остаются независимыми, так как не содержат стили про взаимное позиционирование.

Возможна ошибка в : "шапку (page)" заменить на "шапку (header)".

**Comment by innabelaya** [comment]
@slogoz Спасибо! Исправили https://github.com/bem-site/bem-method/commit/5e197071e6a333888ffbf22582ffaeb060f0470f
