### ISSUE TITLE
Поехала верстка в секции faq

### ISSUE THREAD

**Issue by prog1dev** [bem-site/bem-method#717]
Пример [Зачем-в-именах-модификаторов-и-элементов-указывать-имя-блока](https://ru.bem.info/methodology/faq/#%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%B2-%D0%B8%D0%BC%D0%B5%D0%BD%D0%B0%D1%85-%D0%BC%D0%BE%D0%B4%D0%B8%D1%84%D0%B8%D0%BA%D0%B0%D1%82%D0%BE%D1%80%D0%BE%D0%B2-%D0%B8-%D1%8D%D0%BB%D0%B5%D0%BC%D0%B5%D0%BD%D1%82%D0%BE%D0%B2-%D1%83%D0%BA%D0%B0%D0%B7%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B8%D0%BC%D1%8F-%D0%B1%D0%BB%D0%BE%D0%BA%D0%B0)

Скриншот https://imgur.com/a/sb7dZBv

Chrome 68

**Comment by tadatuta** [comment]
@prog1dev Спасибо!
