### ISSUE TITLE
Неясно, куда должна вести ссылка в англоязычной версии bem-for-js

### ISSUE THREAD

**Issue by ghost** [bem-site/bem-method#721]
В первом предложении под заголовком [Working with redefinition levels](https://github.com/bem-site/bem-method/blob/bem-info-data/method/bem-for-js/bem-for-js.en.md#working-with-redefinition-levels) есть ссылка `[many examples](../filestructure/filestructure.en.md#examples-of-using-redefinition-levels)`. Но коммит 5708de6 [удаляет этот фрагмент](https://github.com/bem-site/bem-method/commit/5708de6cb92739f14afe00fad98cd33472498b29#diff-a5536ade8ceed51a112ed65c4a2cfeb4L247) из файла filestructure.en.md. Так что ссылка не ведёт куда нужно.

Я хотел это исправить, но не знаю, куда она должна вести.
В русскоязычной версии bem-for-js ссылка в этом абзаце ведёт в `../key-concepts/key-concepts.ru.md/#Уровень-переопределения`. Может и англоязычной версии следует вести в `../key-concepts/key-concepts.en.md/#redefinition-level`? Но тогда нужно поменять текст англоязычной версии, потому что там говорится, что по ссылке будут примеры использования, а в key-concepts их нет.
Может быть тогда нужно ссылаться на `../redefinition-levels/redefinition-levels.en.md/#examples-using-redefinition-levels`, куда переехали эти самые примеры? Но так англоязычная и русскоязычная версия будут расходиться.

**Comment by tadatuta** [comment]
cc @godfreyd

**Comment by godfreyd** [comment]
Сейчас посмотрю. @0leynikov, спасибо!

**Comment by godfreyd** [comment]
https://github.com/bem-site/bem-method/pull/723

**Comment by godfreyd** [comment]
Английскую версию поправим, она расходится.
