### ISSUE TITLE
Изображения в bulid неудачно обрезаны 

### ISSUE THREAD

**Issue by ghost** [bem-site/bem-method#728]
На изображениях [build__bem-project.svg](https://github.com/bem-site/bem-method/blob/bem-info-data/method/build/build__bem-project.svg), [build__declaration.svg](https://github.com/bem-site/bem-method/blob/bem-info-data/method/build/build__declaration.svg) и [build__search-form.svg](https://github.com/bem-site/bem-method/blob/bem-info-data/method/build/build__search-form.svg) текст выходит за правый край.

**Comment by godfreyd** [comment]
@0leynikov, можно скрины приложить? У меня все ОК.

**Comment by ghost** [comment]
Ух ты, это интересно. Это оказалось трудно повторить на компьютере с другим разрешением экрана. Я постараюсь найти причину или надёжный способ воспроизвести проблему.

**Comment by ghost** [comment]
На компьютере, где я с этим столкнулся, картинки выглядят так:
![screenshot1](https://user-images.githubusercontent.com/33954227/45828025-27713d00-bce7-11e8-8a3d-21e626fb851f.png)
![screenshot2](https://user-images.githubusercontent.com/33954227/45828041-2e984b00-bce7-11e8-9c75-d8b86bcff369.png)

**Comment by ghost** [comment]
Проблема в неподходящем шрифте. В изображениях указаны Arial и Helvetica, но ближайший (с точки зрения fontconfig) к этому шрифт, установленный у меня — DejaVu Sans.
