### ISSUE TITLE
Битые ссылки в туториале

### ISSUE THREAD

**Issue by shaihulud1992** [bem-site/bem-method#730]
В туториале по БЭМ "Создаем статический БЭМ-проект" (https://ru.bem.info/platform/tutorials/start-with-project-stub/) есть ссылка на файлик bemjson, где лежат ссылки на картинки телефонов (блок goods): https://gist.github.com/innabelaya/b20986600db84c1b8ed229d4a7e012ff

Но, они все битые. Вот, например, картинка, которая не открывается
https://cdn.rawgit.com/bem-site/bem-method/bem-project/articles/start-with-project-stub/iphone7.png

Поэтому после прохождения туториала проект собирается без картинок товаров.

**Comment by godfreyd** [comment]
@shaihulud1992, привет. Спасибо. Поправим.

**Comment by godfreyd** [comment]
https://github.com/bem-site/bem-method/pull/732
