### ISSUE TITLE
Основные понятия — Некорректная ссылка на FAQ

### ISSUE THREAD

**Issue by s0xzwasd** [bem-site/bem-method#731]
[Основные понятия](https://ru.bem.info/methodology/key-concepts/) после объяснения, что такое [элемент](https://ru.bem.info/methodology/key-concepts/#%D0%AD%D0%BB%D0%B5%D0%BC%D0%B5%D0%BD%D1%82) есть ссылка [«Можно ли в методологии БЭМ создавать элементы элементов?»](https://ru.bem.info/methodology/faq/#%D0%9C%D0%BE%D0%B6%D0%BD%D0%BE-%D0%BB%D0%B8-%D1%81%D0%BE%D0%B7%D0%B4%D0%B0%D0%B2%D0%B0%D1%82%D1%8C-%D1%8D%D0%BB%D0%B5%D0%BC%D0%B5%D0%BD%D1%82%D1%8B-%D1%8D%D0%BB%D0%B5%D0%BC%D0%B5%D0%BD%D1%82%D0%BE%D0%B2-block__elem1__elem2), которая уже некорректна, так как этот вопрос-ответ называется теперь по-другому — [Почему не стоит создавать элементы элементов (block__elem1__elem2)?](https://ru.bem.info/methodology/faq/#%D0%9F%D0%BE%D1%87%D0%B5%D0%BC%D1%83-%D0%BD%D0%B5-%D1%81%D1%82%D0%BE%D0%B8%D1%82-%D1%81%D0%BE%D0%B7%D0%B4%D0%B0%D0%B2%D0%B0%D1%82%D1%8C-%D1%8D%D0%BB%D0%B5%D0%BC%D0%B5%D0%BD%D1%82%D1%8B-%D1%8D%D0%BB%D0%B5%D0%BC%D0%B5%D0%BD%D1%82%D0%BE%D0%B2-block__elem1__elem2)

**Comment by godfreyd** [comment]
@tadatuta, нужно обновить сайт, в репозитории все норм: https://github.com/bem-site/bem-method/blob/bem-info-data/method/key-concepts/key-concepts.ru.md#Элемент

**Comment by godfreyd** [comment]
@s0xzwasd, Спасибо! Задачу закрываю.
