### ISSUE TITLE
Не рабоает сайт

### ISSUE THREAD

**Issue by Ivanov-Ruslan** [bem-site/bem-method#740]
Добый день, сайт работает, в разделах с информацией нет ничего, тупо пусто, сайт на профилактике?

**Comment by tadatuta** [comment]
Спасибо, починили.

**Comment by Ivanov-Ruslan** [comment]
спасибо, работает)

чт, 29 нояб. 2018 г. в 16:29, Vladimir Grinenko <notifications@github.com>:
