### ISSUE TITLE
Неверная декларация принципа OCP

### ISSUE THREAD

**Issue by Ne4to777** [bem-site/bem-method#759]
https://ru.bem.info/methodology/css/
Сейчас:
"Любой HTML-элемент страницы должен быть открыт для модификации, но закрыт для изменения"
Необходимо:
"Любой HTML-элемент страницы должен быть открыт для расширения, но закрыт для модификации"

**Comment by godfreyd** [comment]
В БЭМ модификация происходит через дополнительный CSS-класс (модификатор), поэтому ошибок не вижу.
