### ISSUE TITLE
Are you guys related to getbem.com and why the difference in convention?

### ISSUE THREAD

**Issue by woodysee** [bem-site/bem-method#775]
I was doing some reading up on implementing BEM for my SASS modules and have suddenly noticed that there is an alternative BEM standard named "getbem.com" that contradicts the standard set by "Get BEM".

Both standards are also different. For example, "Get BEM" requires modifiers to be separated from blocks and elements with double dashes (i.e. `naming__cell--modifier--small`) while "bem.info" requires modifiers to be separated using a single underscore (i.e. `naming__cell modifier_small`).

I have first learnt about BEM from getbem.com. So the emergence of the standard set by bem.info has presented a dilemma on which source of truth for the BEM methodology I should follow.

Both "Get BEM" and "bem.info" has stated that they at least both done work with Yandex at some point. They even both have the same logo.

So I am wondering if there is any affiliation between "Get BEM" and "bem.info"? And why are two different standards being set on both sites?

Thanks!

**Comment by finngm** [comment]
bem.info does have a page on alternative naming schemes where the "two dashes style" is listed.
https://en.bem.info/methodology/naming-convention/#alternative-naming-schemes
