### ISSUE TITLE
Techs: Create a text about HTML

### ISSUE THREAD

**Issue by varya** [bem-site/bem-method#9]
https://github.com/bem/bem-method/wiki/%D0%A2%D0%B5%D1%85%D0%BD%D0%BE%D0%BB%D0%BE%D0%B3%D0%B8%D0%B8-%D1%80%D0%B5%D0%B0%D0%BB%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D0%B8

Describe HTML in BEM terms. Both HTML+classes and Custom Tags styles.
Here is the link for getting info: http://clubs.ya.ru/bem/replies.xml?item_no=712

Ask vithar@ for a piece of advice.

**Comment by innabelaya** [comment]
https://github.com/bem-site/bem-method/blob/bem-info-data/method/bem-for-html/bem-for-html.ru.md
